//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash_PTranInfo
    {
        public string PK_AccYear { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public int Pk_RecNo { get; set; }
        public string PTranNo { get; set; }
        public string PTranUserID { get; set; }
        public string PTranUserName { get; set; }
        public string PTranTime { get; set; }
        public string LastEditTime { get; set; }
        public string PTranState { get; set; }
        public string PTranMemo { get; set; }
        public Nullable<int> OpenAccMainNo { get; set; }
        public string OpenVouNo { get; set; }
        public string OpenVouKind { get; set; }
    }
}
