//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash_Check
    {
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public string PK_CheckKind { get; set; }
        public string PK_DepositorNo { get; set; }
        public string Depositor { get; set; }
        public string CanUse { get; set; }
        public string UsedMemo { get; set; }
        public string UsedPayee { get; set; }
    }
}
