//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code_Sub
    {
        public string PK_AccYear { get; set; }
        public string PK_SubNo { get; set; }
        public string SubName { get; set; }
        public string SubSNo { get; set; }
        public string DC { get; set; }
        public string AbateKind { get; set; }
        public string CanUse { get; set; }
        public string FK_DSubKind { get; set; }
    }
}
