//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cont_BgtState
    {
        public string PK_AccYear { get; set; }
        public string BgtState { get; set; }
        public string BgtVisaNoPass { get; set; }
        public string BgtVisaNoPay { get; set; }
        public string BgtPay { get; set; }
        public string BgtAdvPay { get; set; }
        public string FasVisaNoPass { get; set; }
        public string FasVisaNoPay { get; set; }
        public string FasPay { get; set; }
        public string FasAdvPay { get; set; }
    }
}
