//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_VisaD
    {
        public string PK_AccYear { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public int PK_VisaNo { get; set; }
        public int PK_VisaDNo { get; set; }
        public string MakeDate { get; set; }
        public string BgtSource { get; set; }
        public string SubNo { get; set; }
        public string MPlanNo { get; set; }
        public string UsageNo { get; set; }
        public string DptBgt { get; set; }
        public string DptUse { get; set; }
        public string PlanNo { get; set; }
        public Nullable<double> ApplyMoney { get; set; }
        public string Dmemo { get; set; }
        public string PayeeName { get; set; }
        public string IsPass { get; set; }
        public string PassDate { get; set; }
        public Nullable<double> PassMoney { get; set; }
        public string PayStyle { get; set; }
        public string AdjustDate { get; set; }
        public Nullable<double> AdjustMoney { get; set; }
        public string IsOk { get; set; }
        public string OkDate { get; set; }
        public string Worker { get; set; }
        public string AccMark { get; set; }
        public string MarkMemo { get; set; }
        public string CaseNo { get; set; }
        public string CaseListKind { get; set; }
        public string SubCity { get; set; }
    }
}
