//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_VouDetail
    {
        public string PK_AccYear { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public string PK_AccType { get; set; }
        public int PK_AccMainNo { get; set; }
        public int PK_DetailNo { get; set; }
        public string DC { get; set; }
        public string SubNo { get; set; }
        public string Memo { get; set; }
        public Nullable<long> Amount { get; set; }
        public string MPlanNo { get; set; }
        public string PlanNo { get; set; }
        public string UsageNo { get; set; }
        public string DptBgt { get; set; }
        public string DptUse { get; set; }
        public string PkindNo { get; set; }
        public string CertNo { get; set; }
        public Nullable<int> CertNum { get; set; }
        public string RelatedVouYear { get; set; }
        public Nullable<int> RelatedVouMNo { get; set; }
        public Nullable<int> RelatedVouDNo { get; set; }
        public string RelatedPayeeJSON { get; set; }
        public Nullable<int> RelatedVisaMNo { get; set; }
        public Nullable<int> RelatedVisaDNo { get; set; }
        public Nullable<int> LinkVouMNo { get; set; }
        public Nullable<int> LinkVouDNo { get; set; }
        public string BudgetSource { get; set; }
        public string CasePayee { get; set; }
        public string CaseNo { get; set; }
        public string CaseListKind { get; set; }
        public string SubCity { get; set; }
        public string InCurDate { get; set; }
        public string FK_OrigFullCode { get; set; }
    }
}
