//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_VouMain
    {
        public string PK_AccYear { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public string PK_AccType { get; set; }
        public int PK_AccMainNo { get; set; }
        public string VouKind { get; set; }
        public string VouScope { get; set; }
        public string VouNo { get; set; }
        public string VouDate { get; set; }
        public string BillDate { get; set; }
        public string BillNo { get; set; }
        public string MainMemo { get; set; }
        public string FK_ExpenseUsageNo { get; set; }
        public Nullable<int> Num { get; set; }
        public string MemoItem { get; set; }
        public string PayWay { get; set; }
        public string Remark1 { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string CaseKindNo { get; set; }
        public string VouSourceNo { get; set; }
        public string SourceDocNo { get; set; }
        public Nullable<System.DateTime> SendNBAADate { get; set; }
        public string NBAAVouNo { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LastModifiedPerson { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
    }
}
