//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_PayeeRecord
    {
        public string PK_AccYear { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public string Pk_PayeeNo { get; set; }
        public string Payee { get; set; }
        public string IDNo { get; set; }
        public string UnifyNo { get; set; }
        public string AreaCode { get; set; }
        public string PayAddress { get; set; }
        public string E_Mail { get; set; }
        public string TelNo { get; set; }
        public string BankNo { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string BankNo_2 { get; set; }
        public string BankName_2 { get; set; }
        public string AccountNo_2 { get; set; }
        public string AccountName_2 { get; set; }
        public string BankNo_3 { get; set; }
        public string BankName_3 { get; set; }
        public string AccountNo_3 { get; set; }
        public string AccountName_3 { get; set; }
        public string Remark { get; set; }
    }
}
