//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_VouCheck
    {
        public string PK_AccYear { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public int PK_AccMainNo { get; set; }
        public string HavePaper { get; set; }
        public string AccCheck { get; set; }
        public string AccDate { get; set; }
        public string AccUser { get; set; }
        public string CashCheck { get; set; }
        public string CashDate { get; set; }
        public string CashUser { get; set; }
        public string FileCheck { get; set; }
        public string FileDate { get; set; }
        public string FileUser { get; set; }
        public string PaperCheck { get; set; }
        public string PaperDate { get; set; }
        public string PaperUser { get; set; }
        public string IsEnd { get; set; }
        public string EndDate { get; set; }
        public string EndUser { get; set; }
        public string Mmemo { get; set; }
        public string IsPrn { get; set; }
    }
}
