//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_BgtIn
    {
        public string PK_AccYear { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public string FK_SubNo { get; set; }
        public string FK_BgtDpt { get; set; }
        public string FK_BgtSource { get; set; }
        public string FK_PlanNo { get; set; }
        public string PassDate { get; set; }
        public Nullable<double> BgtMoney { get; set; }
        public Nullable<double> DistMoney01 { get; set; }
        public Nullable<double> DistMoney02 { get; set; }
        public Nullable<double> DistMoney03 { get; set; }
        public Nullable<double> DistMoney04 { get; set; }
        public Nullable<double> DistMoney05 { get; set; }
        public Nullable<double> DistMoney06 { get; set; }
        public Nullable<double> DistMoney07 { get; set; }
        public Nullable<double> DistMoney08 { get; set; }
        public Nullable<double> DistMoney09 { get; set; }
        public Nullable<double> DistMoney10 { get; set; }
        public Nullable<double> DistMoney11 { get; set; }
        public Nullable<double> DistMoney12 { get; set; }
    }
}
