//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESFAccEntities : DbContext
    {
        public ESFAccEntities()
            : base("name=ESFAccEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Notice_Detail> Notice_Detail { get; set; }
        public virtual DbSet<Notice_Kind> Notice_Kind { get; set; }
        public virtual DbSet<Notice_Main> Notice_Main { get; set; }
        public virtual DbSet<Pow_FuncGrp> Pow_FuncGrp { get; set; }
        public virtual DbSet<Pow_Level> Pow_Level { get; set; }
        public virtual DbSet<Pow_User> Pow_User { get; set; }
        public virtual DbSet<Pow_User_DptSet> Pow_User_DptSet { get; set; }
        public virtual DbSet<Pow_User_FuncGrp> Pow_User_FuncGrp { get; set; }
        public virtual DbSet<Pow_User_Level> Pow_User_Level { get; set; }
    }
}
