//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lck_Unit
    {
        public string PK_AccYear { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public string AccMon01 { get; set; }
        public string AccLock01 { get; set; }
        public string AccMon02 { get; set; }
        public string AccLock02 { get; set; }
        public string AccMon03 { get; set; }
        public string AccLock03 { get; set; }
        public string AccMon04 { get; set; }
        public string AccLock04 { get; set; }
        public string AccMon05 { get; set; }
        public string AccLock05 { get; set; }
        public string AccMon06 { get; set; }
        public string AccLock06 { get; set; }
        public string AccMon07 { get; set; }
        public string AccLock07 { get; set; }
        public string AccMon08 { get; set; }
        public string AccLock08 { get; set; }
        public string AccMon09 { get; set; }
        public string AccLock09 { get; set; }
        public string AccMon10 { get; set; }
        public string AccLock10 { get; set; }
        public string AccMon11 { get; set; }
        public string AccLock11 { get; set; }
        public string AccMon12 { get; set; }
        public string AccLock12 { get; set; }
    }
}
