//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lck_UnitFas
    {
        public string PK_AccYear { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public string FasAcc01 { get; set; }
        public string FasLock01 { get; set; }
        public string FasAcc02 { get; set; }
        public string FasLock02 { get; set; }
        public string FasAcc03 { get; set; }
        public string FasLock03 { get; set; }
    }
}
