//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lck_Sum
    {
        public string PK_AccYear { get; set; }
        public string FK_FundNo { get; set; }
        public string SumMon01 { get; set; }
        public string SumMon02 { get; set; }
        public string SumMon03 { get; set; }
        public string SumMon04 { get; set; }
        public string SumMon05 { get; set; }
        public string SumMon06 { get; set; }
        public string SumMon07 { get; set; }
        public string SumMon08 { get; set; }
        public string SumMon09 { get; set; }
        public string SumMon10 { get; set; }
        public string SumMon11 { get; set; }
        public string SumMon12 { get; set; }
        public string SumFas01 { get; set; }
        public string SumFas02 { get; set; }
        public string SumFas03 { get; set; }
    }
}
