//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merge_Vou
    {
        public string PK_AccYear { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public int PK_MainNo { get; set; }
        public string F_MakeDate { get; set; }
        public string F_MakeNo { get; set; }
        public string F_PassDate { get; set; }
        public string F_PassNo { get; set; }
        public string F_Voukind { get; set; }
        public int PK_AccMainNo { get; set; }
        public string VouDate { get; set; }
        public string VouNo { get; set; }
        public string BillDate { get; set; }
        public string BillNo { get; set; }
        public string VouKind { get; set; }
        public string LogSource { get; set; }
        public string MergeState { get; set; }
        public string MergeCreateTime { get; set; }
        public string MergeLstTime { get; set; }
    }
}
