//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merge_Visa
    {
        public string PK_AccYear { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public int PK_OrigVisaNo { get; set; }
        public string OrigMakeDate { get; set; }
        public string OrigDepanNo { get; set; }
        public int PK_VisaNo { get; set; }
        public string MMakeDate { get; set; }
        public string DepanNo { get; set; }
        public string LogSource { get; set; }
        public string MergeState { get; set; }
        public string MergeCreateTime { get; set; }
        public string MergeLstTime { get; set; }
    }
}
