//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice_Vou
    {
        public string FK_NoticeKind { get; set; }
        public int PK_NoticeNo { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public string OpenVouCode { get; set; }
        public string OpenVouKind { get; set; }
        public Nullable<int> IsVouAccMainNo { get; set; }
        public string IsVouNo { get; set; }
        public string IsOpenVou { get; set; }
    }
}
