//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pow_User
    {
        public string PK_AccYear { get; set; }
        public int PK_UserNo { get; set; }
        public string FK_FundNo { get; set; }
        public string FK_UnitNo { get; set; }
        public string FK_DptNo { get; set; }
        public string Account_AD { get; set; }
        public string UserName { get; set; }
        public string UnitName_AD { get; set; }
        public string DptName_AD { get; set; }
        public string UserTitle_AD { get; set; }
        public string UserID { get; set; }
        public string SerialNo { get; set; }
        public string PinNo { get; set; }
        public string UserTel { get; set; }
        public string UserTelExt { get; set; }
        public string UserEMail { get; set; }
        public string CanUse { get; set; }
        public string IsAcc { get; set; }
        public string DefaultAccYear { get; set; }
        public string UMemo1 { get; set; }
        public string UMemo2 { get; set; }
    }
}
