//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionGroupMenu.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pow_Func
    {
        public int PK_FuncNo { get; set; }
        public string FuncCode { get; set; }
        public string FuncName { get; set; }
        public string FuncPgSys { get; set; }
        public string FuncPgName { get; set; }
        public string FuncOriginalNo { get; set; }
        public string FuncMemo { get; set; }
        public string FuncLevel { get; set; }
        public string FuncAcc { get; set; }
        public string IsFunc { get; set; }
        public string CanUse { get; set; }
        public string DefaultUse { get; set; }
        public string DefaultAdd { get; set; }
        public string DefaultEdit { get; set; }
        public string DefaultDel { get; set; }
        public string DefaultPass { get; set; }
    }
}
